# Sử dụng image Python chính thức
FROM python:3.9-slim

# Cài đặt các thư viện cần thiết
WORKDIR /app
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Sao chép mã nguồn vào container
COPY . .

# Cổng mà ứng dụng sẽ chạy
EXPOSE 5000

# Lệnh để chạy ứng dụng Python
CMD ["python", "app.py"]
